# Generated by Django 3.1.14 on 2024-05-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20240515_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='next_evolution',
        ),
    ]
