# Generated by Django 3.1.14 on 2024-05-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20240525_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Endurance',
            new_name='endurance',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Protection',
            new_name='protection',
        ),
    ]
